In [12]:
import pandas as pd
import numpy as np

df = pd.read_csv('../data/processed/df_tripdata_engineered_with_total.csv')
df.head()

,ID_CODE,SURVEY_TIMESTAMP,FFDAYS2,HRSF,KOD,MODE_F,CNTRBTRS,IMP_REC,avg_wind_speed,avg_wind_gust,...,water_level_rose,water_level_fell,was_sunrise,was_sunset,was_moonrise,was_moonset,moon_phase_age,sun_distance,moon_distance,total_catch
0,1000920140505017,2014-05-05 17:00:00,0.0,6.0,wd,7.0,1.0,0.0,6.225000,7.441667,...,1,1,0,0,1,0,5.633444,1.508852e+08,404508.533199,0.0
1,1000920140505018,2014-05-05 17:00:00,0.0,6.0,wd,7.0,1.0,0.0,6.225000,7.441667,...,1,1,0,0,1,0,5.633444,1.508852e+08,404508.533199,0.0
2,1000920150620006,2015-06-20 16:00:00,0.0,4.5,we,8.0,1.0,0.0,5.946667,7.013333,...,1,1,0,0,0,0,3.611222,1.520199e+08,397917.383118,1.0
3,1000920150627020,2015-06-27 17:00:00,3.0,7.0,we,8.0,0.0,0.0,7.223810,8.509524,...,1,1,0,0,1,0,9.600111,1.520708e+08,400109.337422,0.0
4,1000920150711002,2015-07-11 11:00:00,1.0,2.0,we,8.0,1.0,0.0,3.566667,4.250000,...,1,0,0,0,0,0,23.600111,1.520861e+08,372690.223940,0.0

In [13]:
df.columns

Index(['ID_CODE', 'SURVEY_TIMESTAMP', 'FFDAYS2', 'HRSF', 'KOD', 'MODE_F',
       'CNTRBTRS', 'IMP_REC', 'avg_wind_speed', 'avg_wind_gust',
       'wind_speed_rose', 'wind_speed_fell', 'avg_air_pressure',
       'air_pressure_rose', 'air_pressure_fell', 'avg_air_temp_c',
       'air_temp_rose', 'air_temp_fell', 'avg_water_temp_c', 'water_temp_rose',
       'water_temp_fell', 'avg_water_level', 'water_level_rose',
       'water_level_fell', 'was_sunrise', 'was_sunset', 'was_moonrise',
       'was_moonset', 'moon_phase_age', 'sun_distance', 'moon_distance',
       'total_catch'],
      dtype='object')

In [14]:
df["hour"] = pd.to_datetime(df["SURVEY_TIMESTAMP"]).dt.hour
df["day"] = pd.to_datetime(df["SURVEY_TIMESTAMP"]).dt.day
df["month"] = pd.to_datetime(df["SURVEY_TIMESTAMP"]).dt.month
df.columns

Index(['ID_CODE', 'SURVEY_TIMESTAMP', 'FFDAYS2', 'HRSF', 'KOD', 'MODE_F',
       'CNTRBTRS', 'IMP_REC', 'avg_wind_speed', 'avg_wind_gust',
       'wind_speed_rose', 'wind_speed_fell', 'avg_air_pressure',
       'air_pressure_rose', 'air_pressure_fell', 'avg_air_temp_c',
       'air_temp_rose', 'air_temp_fell', 'avg_water_temp_c', 'water_temp_rose',
       'water_temp_fell', 'avg_water_level', 'water_level_rose',
       'water_level_fell', 'was_sunrise', 'was_sunset', 'was_moonrise',
       'was_moonset', 'moon_phase_age', 'sun_distance', 'moon_distance',
       'total_catch', 'hour', 'day', 'month'],
      dtype='object')

In [15]:
df = pd.get_dummies(df, columns=["KOD"], drop_first=True)
df.head()

,ID_CODE,SURVEY_TIMESTAMP,FFDAYS2,HRSF,MODE_F,CNTRBTRS,IMP_REC,avg_wind_speed,avg_wind_gust,wind_speed_rose,...,was_moonrise,was_moonset,moon_phase_age,sun_distance,moon_distance,total_catch,hour,day,month,KOD_we
0,1000920140505017,2014-05-05 17:00:00,0.0,6.0,7.0,1.0,0.0,6.225000,7.441667,1,...,1,0,5.633444,1.508852e+08,404508.533199,0.0,17,5,5,False
1,1000920140505018,2014-05-05 17:00:00,0.0,6.0,7.0,1.0,0.0,6.225000,7.441667,1,...,1,0,5.633444,1.508852e+08,404508.533199,0.0,17,5,5,False
2,1000920150620006,2015-06-20 16:00:00,0.0,4.5,8.0,1.0,0.0,5.946667,7.013333,0,...,0,0,3.611222,1.520199e+08,397917.383118,1.0,16,20,6,True
3,1000920150627020,2015-06-27 17:00:00,3.0,7.0,8.0,0.0,0.0,7.223810,8.509524,1,...,1,0,9.600111,1.520708e+08,400109.337422,0.0,17,27,6,True
4,1000920150711002,2015-07-11 11:00:00,1.0,2.0,8.0,1.0,0.0,3.566667,4.250000,0,...,0,0,23.600111,1.520861e+08,372690.223940,0.0,11,11,7,True

In [17]:
df = df.drop(columns=["SURVEY_TIMESTAMP"])
df = df.drop(columns=["ID_CODE"])

X = df.drop(columns=["total_catch"])
y = df["total_catch"]

In [18]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Ridge
from sklearn.pipeline import Pipeline

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = Pipeline([
    ("scaler", StandardScaler()),
    ("ridge", Ridge(alpha=1.0))
])

model.fit(X_train, y_train)

print("Train score:", model.score(X_train, y_train))
print("Test score:", model.score(X_test, y_test))

Train score: 0.08026880208924114
Test score: 0.06381979587254938

In [20]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error

# Train/test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# --- Model ---
model = RandomForestRegressor(
    n_estimators=1000,   # number of trees
    max_depth=None,     # let trees grow fully
    random_state=42,
    n_jobs=-1           # use all CPU cores
)

model.fit(X_train, y_train)

# --- Evaluation ---
preds = model.predict(X_test)

rmse = mean_squared_error(y_test, preds) ** 0.5
print("RMSE:", rmse)
print("R^2:", model.score(X_test, y_test))

RMSE: 11.905559044959938
R^2: 0.3206178207658601

In [22]:
importances = pd.Series(model.feature_importances_, index=X.columns)
print(importances.sort_values(ascending=False).head(15))
print(importances.sort_values(ascending=False).tail(15))

avg_air_pressure    0.075806
moon_distance       0.075469
avg_water_level     0.072944
avg_water_temp_c    0.072870
sun_distance        0.067723
avg_air_temp_c      0.065576
FFDAYS2             0.062909
hour                0.059843
MODE_F              0.058907
HRSF                0.055347
avg_wind_gust       0.052076
avg_wind_speed      0.048861
moon_phase_age      0.046373
day                 0.042066
CNTRBTRS            0.033546
dtype: float64
air_pressure_fell    0.006512
water_temp_rose      0.006379
KOD_we               0.006033
air_temp_fell        0.005912
was_moonset          0.005877
water_temp_fell      0.005855
water_level_fell     0.005851
wind_speed_rose      0.005712
air_temp_rose        0.005000
was_moonrise         0.004866
water_level_rose     0.004827
air_pressure_rose    0.004064
wind_speed_fell      0.004043
was_sunrise          0.003861
was_sunset           0.000552
dtype: float64