In [2]:
import pandas as pd 

df = pd.read_csv('../data/processed/df_tripdata_engineered.csv')
df.head()

,ID_CODE,SURVEY_TIMESTAMP,FFDAYS2,HRSF,KOD,MODE_F,CNTRBTRS,IMP_REC,ATLANTIC COD,ATLANTIC CROAKER,...,avg_water_level,water_level_rose,water_level_fell,was_sunrise,was_sunset,was_moonrise,was_moonset,moon_phase_age,sun_distance,moon_distance
0,1000920140505017,2014-05-05 17:00:00,0.0,6.0,wd,7.0,1.0,0.0,0.0,0.0,...,0.491667,1,1,0,0,1,0,5.633444,1.508852e+08,404508.533199
1,1000920140505018,2014-05-05 17:00:00,0.0,6.0,wd,7.0,1.0,0.0,0.0,0.0,...,0.491667,1,1,0,0,1,0,5.633444,1.508852e+08,404508.533199
2,1000920150620006,2015-06-20 16:00:00,0.0,4.5,we,8.0,1.0,0.0,0.0,0.0,...,0.442800,1,1,0,0,0,0,3.611222,1.520199e+08,397917.383118
3,1000920150627020,2015-06-27 17:00:00,3.0,7.0,we,8.0,0.0,0.0,0.0,0.0,...,1.628286,1,1,0,0,1,0,9.600111,1.520708e+08,400109.337422
4,1000920150711002,2015-07-11 11:00:00,1.0,2.0,we,8.0,1.0,0.0,0.0,0.0,...,2.077000,1,0,0,0,0,0,23.600111,1.520861e+08,372690.223940

In [3]:
df.columns

Index(['ID_CODE', 'SURVEY_TIMESTAMP', 'FFDAYS2', 'HRSF', 'KOD', 'MODE_F',
       'CNTRBTRS', 'IMP_REC', 'ATLANTIC COD', 'ATLANTIC CROAKER',
       'ATLANTIC HERRING', 'ATLANTIC MACKEREL', 'ATLANTIC MENHADEN',
       'BLACK SEA BASS', 'BLUEFISH', 'CHUB MACKEREL', 'CUNNER',
       'DOGFISH SHARK', 'GRAY SNAPPER', 'GRAY TRIGGERFISH', 'HICKORY SHAD',
       'LITTLE TUNNY', 'NORTHERN KINGFISH', 'NORTHERN PUFFER',
       'OYSTER TOADFISH', 'PINFISH', 'RED DRUM', 'RED HAKE', 'SCUP',
       'SEAROBIN GENUS', 'SKATE GENUS', 'SOUTHERN KINGFISH',
       'SPANISH MACKEREL', 'SPOT', 'SPOTTED SEATROUT', 'STRIPED BASS',
       'SUMMER FLOUNDER', 'TAUTOG', 'UNIDENTIFIED (SHARKS)',
       'UNIDENTIFIED SKATE OR RAY', 'WEAKFISH', 'WINDOWPANE',
       'WINTER FLOUNDER', 'avg_wind_speed', 'avg_wind_gust', 'wind_speed_rose',
       'wind_speed_fell', 'avg_air_pressure', 'air_pressure_rose',
       'air_pressure_fell', 'avg_air_temp_c', 'air_temp_rose', 'air_temp_fell',
       'avg_water_temp_c', 'water_temp_rose', 'water_temp_fell',
       'avg_water_level', 'water_level_rose', 'water_level_fell',
       'was_sunrise', 'was_sunset', 'was_moonrise', 'was_moonset',
       'moon_phase_age', 'sun_distance', 'moon_distance'],
      dtype='object')

In [4]:
fishcols = ['ATLANTIC COD', 'ATLANTIC CROAKER',
       'ATLANTIC HERRING', 'ATLANTIC MACKEREL', 'ATLANTIC MENHADEN',
       'BLACK SEA BASS', 'BLUEFISH', 'CHUB MACKEREL', 'CUNNER',
       'DOGFISH SHARK', 'GRAY SNAPPER', 'GRAY TRIGGERFISH', 'HICKORY SHAD',
       'LITTLE TUNNY', 'NORTHERN KINGFISH', 'NORTHERN PUFFER',
       'OYSTER TOADFISH', 'PINFISH', 'RED DRUM', 'RED HAKE', 'SCUP',
       'SEAROBIN GENUS', 'SKATE GENUS', 'SOUTHERN KINGFISH',
       'SPANISH MACKEREL', 'SPOT', 'SPOTTED SEATROUT', 'STRIPED BASS',
       'SUMMER FLOUNDER', 'TAUTOG', 'UNIDENTIFIED (SHARKS)',
       'UNIDENTIFIED SKATE OR RAY', 'WEAKFISH', 'WINDOWPANE',
       'WINTER FLOUNDER']

In [5]:
df["total_catch"] = df[fishcols].sum(axis=1)

In [8]:
df.head(100)

,ID_CODE,SURVEY_TIMESTAMP,FFDAYS2,HRSF,KOD,MODE_F,CNTRBTRS,IMP_REC,ATLANTIC COD,ATLANTIC CROAKER,...,water_level_rose,water_level_fell,was_sunrise,was_sunset,was_moonrise,was_moonset,moon_phase_age,sun_distance,moon_distance,total_catch
0,1000920140505017,2014-05-05 17:00:00,0.0,6.0,wd,7.0,1.0,0.0,0.0,0.0,...,1,1,0,0,1,0,5.633444,1.508852e+08,404508.533199,0.000000
1,1000920140505018,2014-05-05 17:00:00,0.0,6.0,wd,7.0,1.0,0.0,0.0,0.0,...,1,1,0,0,1,0,5.633444,1.508852e+08,404508.533199,0.000000
2,1000920150620006,2015-06-20 16:00:00,0.0,4.5,we,8.0,1.0,0.0,0.0,0.0,...,1,1,0,0,0,0,3.611222,1.520199e+08,397917.383118,1.000000
3,1000920150627020,2015-06-27 17:00:00,3.0,7.0,we,8.0,0.0,0.0,0.0,0.0,...,1,1,0,0,1,0,9.600111,1.520708e+08,400109.337422,0.000000
4,1000920150711002,2015-07-11 11:00:00,1.0,2.0,we,8.0,1.0,0.0,0.0,0.0,...,1,0,0,0,0,0,23.600111,1.520861e+08,372690.223940,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1104820141107005,2014-11-07 14:00:00,0.0,3.5,we,7.0,3.0,0.0,0.0,0.0,...,1,0,0,0,0,0,14.500111,1.482495e+08,378252.677109,16.491065
96,1104820150812020,2015-08-12 17:00:00,0.0,3.0,wd,7.0,2.0,0.0,0.0,0.0,...,0,1,0,0,0,0,26.166778,1.515970e+08,390160.747027,1.000000
97,1104920150811001,2015-08-11 13:00:00,0.0,3.0,wd,5.0,1.0,0.0,0.0,0.0,...,1,0,0,0,0,0,25.233444,1.516258e+08,387118.560619,8.185507
98,1104920150811002,2015-08-11 13:00:00,0.0,3.0,wd,5.0,1.0,0.0,0.0,0.0,...,1,0,0,0,0,0,25.233444,1.516258e+08,387118.560619,0.000000
99,1105220160906003,2016-09-06 15:00:00,0.0,4.0,wd,7.0,2.0,0.0,0.0,0.0,...,1,1,0,0,1,0,4.544556,1.507702e+08,407221.768857,0.000000

In [14]:
df.drop(columns=fishcols, inplace=True)
df.columns

KeyError: "['ATLANTIC COD', 'ATLANTIC CROAKER', 'ATLANTIC HERRING', 'ATLANTIC MACKEREL', 'ATLANTIC MENHADEN', 'BLACK SEA BASS', 'BLUEFISH', 'CHUB MACKEREL', 'CUNNER', 'DOGFISH SHARK', 'GRAY SNAPPER', 'GRAY TRIGGERFISH', 'HICKORY SHAD', 'LITTLE TUNNY', 'NORTHERN KINGFISH', 'NORTHERN PUFFER', 'OYSTER TOADFISH', 'PINFISH', 'RED DRUM', 'RED HAKE', 'SCUP', 'SEAROBIN GENUS', 'SKATE GENUS', 'SOUTHERN KINGFISH', 'SPANISH MACKEREL', 'SPOT', 'SPOTTED SEATROUT', 'STRIPED BASS', 'SUMMER FLOUNDER', 'TAUTOG', 'UNIDENTIFIED (SHARKS)', 'UNIDENTIFIED SKATE OR RAY', 'WEAKFISH', 'WINDOWPANE', 'WINTER FLOUNDER'] not found in axis"

In [13]:
df.to_csv('../data/processed/df_tripdata_engineered_with_total.csv', index=False)